### ISSUE TITLE
How to extract group adresses, datapoints, names, and attributes for devices in the sets file ?

### ISSUE THREAD

**Issue by telemac** [vapourismo/ets-go#1]
What would be the procedure to extract the meaning bits of a project ?

A function that returns structured data easy to manipulate from a knx project would be really valuable.

Thank you for all your really great and useful work about knx and go.

**Comment by vapourismo** [comment]
Indeed it would. I haven't come around to thinking about that properly, though.

The structure of an .knxproj archive is kind of fragile. While most projects have only one installation file, and everything about the project is stored in there, it is definitely possible to structure a project into more installations. Reading all installations at once can be very resource-intense, hence the seperation of [ProjectFile](https://godoc.org/github.com/vapourismo/ets-go/ets#ProjectFile) into multiple [InstallationFile](https://godoc.org/github.com/vapourismo/ets-go/ets#InstallationFile)s.

A method on `ProjectFile` which reads all installations sequentially and compiles them into one big `Project` sounds reasonable to me. Would that suite your needs?

**Comment by telemac** [comment]
Absolutely, i started to code something like this, but i don't have your knowledge of the knx world, so i have to figure out the structure of the knxproj, which seems a bit overcomplicated to me.

**Comment by vapourismo** [comment]
Basically, the structure of this package maps onto the structure of a .knxproj.

You are absolutely right, it is overly complicated. But that's KNX.

**Comment by vapourismo** [comment]
Can you try the `feature/decode-entire-project` branch for me? `ProjectFile.Decode` now decodes the entire project.

**Comment by telemac** [comment]
The modification you made merge multiple installations in the Project structure. I was thinking of something involving more processing, with a few nested loops, like this :

Installations
  Topology
    Lines
      Devices
        ComObjects
          Connectors

and in GroupAddresses end sub structures as well

store the ids in maps, and get back a map indexed by group address, giving the corresponding name and datapoint, and may be other informations (area, line, device names)

Looping thru multiple installations is not a big deal, and as it reflects the knxproj structure, it is probably better to keep your original decoding.

I started to work on this, i'll post my results when i'll finish.

**Comment by vapourismo** [comment]
That would be possible, but Area/Line/Device aswell as GroupRange/GroupAddress structures aren't flat. They are trees. Also they can be nested at 1, 2 or 3 levels deep. How do you accommodate for that?

**Comment by telemac** [comment]
This is a first version, i think to handle the nested nature of knxproj i'll have to make functions that call themselves recursively. The few projects that i have don't have multiple levels. This serves my actuel need pretty well but it is not general, nor absolutely correct. It's a starting point.
```
package main

import (
	"encoding/json"
	"fmt"
	"log"

	"github.com/vapourismo/ets-go/ets"
	"github.com/vapourismo/knx-go/knx/cemi"
)

func main() {
	ga, err := ExportGroupAdresses("FORMATION_EXEMPLE.knxproj")
	if err != nil {
		log.Println(err)
	}

	fmt.Println(ToJSON(ga))
}

//-------------------------------------------------------------------------------

// ToJSON returns a json string representing the interface or "" on error
func ToJSON(i interface{}) string {
	json, err := json.Marshal(i)
	if err != nil {
		return ""
	}
	return string(json)
}

// GroupAddressExt stores information for a group address, including the datapoint type
type GroupAddressExt struct {
	ets.GroupAddress
	Datapoint  string
	GroupRange string
	SubRange   string
	Addr3      string
}

func (gae *GroupAddressExt) set(ga ets.GroupAddress) {
	gae.Address = ga.Address
	gae.ID = ga.ID
	gae.Name = ga.Name
	gae.Addr3 = cemi.GroupAddr(ga.Address).String()
}

// GroupAddressExtMap is a map of GroupAddressExt indexed by the group address
type GroupAddressExtMap map[uint]*GroupAddressExt

// AddGroupAddr adds a GroupAddressExt to the GroupAddressExtMap map
func (gaem *GroupAddressExtMap) AddGroupAddr(gae GroupAddressExt) {
	(*gaem)[gae.Address] = &gae
}

func (gaem *GroupAddressExtMap) setDatapointByID(id ets.GroupAddressID, datapoint string) error {
	for _, gae := range *gaem {
		if gae.ID == id {
			var a, b int
			n, err := fmt.Sscanf(datapoint, "DPST-%d-%d", &a, &b)
			if err == nil && n == 2 {
				gae.Datapoint = fmt.Sprintf("%d.%03d", a, b)
				return nil
			}
		}
	}
	return fmt.Errorf("group address %d not found", id)
}

// ExportGroupAdresses takes a .knxproj file and returns a map of the group address contained in the project
func ExportGroupAdresses(knxProj string) (GroupAddressExtMap, error) {
	gaeMap := make(GroupAddressExtMap)
	archive, err := ets.OpenExportArchive(knxProj)
	if err != nil {
		return gaeMap, err
	}
	defer archive.Close()

	for _, projFile := range archive.ProjectFiles {
		/*
			projInfo, err := projFile.Decode()
			if err != nil {
				log.Println(err)
				continue
			}

			fmt.Printf("projInfo %s", ToJSON(projInfo))
		*/
		for _, instFile := range projFile.InstallationFiles {
			proj, err := instFile.Decode()
			if err != nil {
				log.Println(err)
				continue
			}

			//fmt.Println("proj", ToJSON(proj))

			// Loop on all installations in project file
			for _, inst := range proj.Installations {
				//fmt.Printf("Installation %s %s\n", inst.Name, ToJSON(inst))
				//inst.GroupAddresses[0].SubRanges[0].SubRanges[0]...

				// Loop inside GroupAddresses and gather all GA
				for _, ga := range inst.GroupAddresses {
					//fmt.Printf("ga %s %s\n", ga.Name, ToJSON(ga))

					for _, subRange := range ga.SubRanges {
						//fmt.Printf("subRange %s %s\n", subRange.Name, ToJSON(subRange))
						// Here we get the group adresses
						for _, address := range subRange.Addresses {
							//fmt.Printf("address %s/%s/%s %s\n", ga.Name, subRange.Name, address.Name, ToJSON(address))
							var gae GroupAddressExt
							gae.set(address)
							gae.GroupRange = ga.Name
							gae.SubRange = subRange.Name
							gaeMap.AddGroupAddr(gae)
						}
					}
					/*
						for _, adress := range ga.Addresses {
							fmt.Printf("adress %s %s\n", adress.Name, ToJSON(adress))
						}
					*/
				}

				for _, area := range inst.Topology {
					for _, line := range area.Lines {
						for _, device := range line.Devices {
							//fmt.Printf("area %s, line %s, device %s\n", area.Name, line.Name, device.Name)
							for _, comObject := range device.ComObjects {
								if comObject.DatapointType != "" && len(comObject.Connectors) > 0 {
									//fmt.Printf("comObject %s %s\n", comObject.DatapointType, ToJSON(comObject))
									for _, connector := range comObject.Connectors {
										//fmt.Printf("connector %s %s\n", connector.RefID, ToJSON(connector))
										gaeMap.setDatapointByID(connector.RefID, comObject.DatapointType)
									}
								}
							}
						}
					}
				}
			}
		}

	}

	//fmt.Printf("gaeMaps %s\n", ToJSON(gaeMap))

	return gaeMap, nil
}
```

**Comment by vapourismo** [comment]
Please fork the repository and apply the patch to your repository. Then submit it as a Pull Request.

**Comment by telemac** [comment]
This was working with ETS 5.5.3 but it seems that the 5.5.4 version altered the way the datapoint types are stored. I have to figure out what changed.

**Comment by JoseAndresMR** [comment]
Hello guys and sorry for commenting a closed issue.

I have read all your conversation and this is just what I'm looking for: decode a .knxproject into a json/csv file so I can code over it (to write its OpenHAB KNX binding directly from it). But it seems to me like feature/decode-entire-project isn't updated with that code.

I'm new at Go, so probably I missed something relevant. Would strongly appreciate some guidance to find it or another way to solve the problem.

Thank you so much!

**Comment by vapourismo** [comment]
Have a look at the docs first: https://godoc.org/github.com/vapourismo/ets-go/ets
