### ISSUE TITLE
XML namespace

### ISSUE THREAD

**Issue by vgraveto** [vapourismo/ets-go#2]
Hello,

Are you still using this package?

I was trying to use it with ETS 5 and discovered that exists a new schema "http://knx.org/xml/project/20", the version 2.0 of the XML schema.

Do you intend to update the repo? Does it exist other framework for go with this same propose ?

I could try to help updating to include the new schema

Regards,
Vitor

**Comment by vapourismo** [comment]
I do not intend to update this repository for schema version 2.0. 

If you chose to fit this package to the new version, I would gladly review a PR.
